language: c
compiler:
  - clang
  - gcc
install: 
  - sudo sh .travis/add-trusty
  - sudo apt-get update
  - sudo apt-get -t trusty install automake
  - sudo apt-get install docbook-utils
  - automake --version
script: ./autogen.sh && dpkg-buildpackage -rfakeroot -uc -us -i -I.git
